// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: tee/proto/tee_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TeeExecution_Execute_FullMethodName         = "/teeservice.TeeExecution/Execute"
	TeeExecution_GetRegions_FullMethodName      = "/teeservice.TeeExecution/GetRegions"
	TeeExecution_GetAttestations_FullMethodName = "/teeservice.TeeExecution/GetAttestations"
)

// TeeExecutionClient is the client API for TeeExecution service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeeExecutionClient interface {
	Execute(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResult, error)
	GetRegions(ctx context.Context, in *GetRegionsRequest, opts ...grpc.CallOption) (*GetRegionsResponse, error)
	GetAttestations(ctx context.Context, in *GetAttestationsRequest, opts ...grpc.CallOption) (*RegionAttestations, error)
}

type teeExecutionClient struct {
	cc grpc.ClientConnInterface
}

func NewTeeExecutionClient(cc grpc.ClientConnInterface) TeeExecutionClient {
	return &teeExecutionClient{cc}
}

func (c *teeExecutionClient) Execute(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResult)
	err := c.cc.Invoke(ctx, TeeExecution_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teeExecutionClient) GetRegions(ctx context.Context, in *GetRegionsRequest, opts ...grpc.CallOption) (*GetRegionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRegionsResponse)
	err := c.cc.Invoke(ctx, TeeExecution_GetRegions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teeExecutionClient) GetAttestations(ctx context.Context, in *GetAttestationsRequest, opts ...grpc.CallOption) (*RegionAttestations, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegionAttestations)
	err := c.cc.Invoke(ctx, TeeExecution_GetAttestations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeeExecutionServer is the server API for TeeExecution service.
// All implementations must embed UnimplementedTeeExecutionServer
// for forward compatibility.
type TeeExecutionServer interface {
	Execute(context.Context, *ExecutionRequest) (*ExecutionResult, error)
	GetRegions(context.Context, *GetRegionsRequest) (*GetRegionsResponse, error)
	GetAttestations(context.Context, *GetAttestationsRequest) (*RegionAttestations, error)
	mustEmbedUnimplementedTeeExecutionServer()
}

// UnimplementedTeeExecutionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeeExecutionServer struct{}

func (UnimplementedTeeExecutionServer) Execute(context.Context, *ExecutionRequest) (*ExecutionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedTeeExecutionServer) GetRegions(context.Context, *GetRegionsRequest) (*GetRegionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegions not implemented")
}
func (UnimplementedTeeExecutionServer) GetAttestations(context.Context, *GetAttestationsRequest) (*RegionAttestations, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttestations not implemented")
}
func (UnimplementedTeeExecutionServer) mustEmbedUnimplementedTeeExecutionServer() {}
func (UnimplementedTeeExecutionServer) testEmbeddedByValue()                      {}

// UnsafeTeeExecutionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeeExecutionServer will
// result in compilation errors.
type UnsafeTeeExecutionServer interface {
	mustEmbedUnimplementedTeeExecutionServer()
}

func RegisterTeeExecutionServer(s grpc.ServiceRegistrar, srv TeeExecutionServer) {
	// If the following call pancis, it indicates UnimplementedTeeExecutionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TeeExecution_ServiceDesc, srv)
}

func _TeeExecution_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeeExecutionServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeeExecution_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeeExecutionServer).Execute(ctx, req.(*ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeeExecution_GetRegions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeeExecutionServer).GetRegions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeeExecution_GetRegions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeeExecutionServer).GetRegions(ctx, req.(*GetRegionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeeExecution_GetAttestations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttestationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeeExecutionServer).GetAttestations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeeExecution_GetAttestations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeeExecutionServer).GetAttestations(ctx, req.(*GetAttestationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TeeExecution_ServiceDesc is the grpc.ServiceDesc for TeeExecution service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeeExecution_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "teeservice.TeeExecution",
	HandlerType: (*TeeExecutionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _TeeExecution_Execute_Handler,
		},
		{
			MethodName: "GetRegions",
			Handler:    _TeeExecution_GetRegions_Handler,
		},
		{
			MethodName: "GetAttestations",
			Handler:    _TeeExecution_GetAttestations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tee/proto/tee_service.proto",
}
